ktor:
    application:
        modules:
            - com.example.ApplicationKt.module
    deployment:
        port: 8080

    data-source:
        host: "$DB_HOST:localhost"
        port: "$DB_PORT:8529"
        user: "$DB_USER:root"
        password: "$DB_PASSWORD:password"
        database: "$DB_NAME:example"
        max-connection: 10